Add configurable product stock counter with condition
scandipwa/urlrewrite-graphql pull request #4
Opened 2021-01-28 08:06 UTC by winniepukki

2021-02-01 14:00 UTC, alfredsgenkins approved these changes
Seems OK, but this logic becomes more and more complex.

You handled the simple and configurable cases - what about bundle items? Also, does this respects the "disabled" stock tracking (or how it's correctly named)? @lianastaskevica did QA check all above cases?

2021-02-01 14:28 UTC, lianastaskevica commented
> Seems OK, but this logic becomes more and more complex.
> 
> You handled the simple and configurable cases - what about bundle items? Also, does this respects the "disabled" stock tracking (or how it's correctly named)? @lianastaskevica did QA check all above cases?

@alfredsgenkins we cannot QA BE changes. @winniepukki please test your solution for all product types and update us here on the status.

2021-02-02 23:44 UTC, winniepukki commented
@alfredsgenkins @lianastaskevica failed for the Bundle type. Everything else that has been tested with my local set-up passed with all possible scenarios

2021-02-15 11:04 UTC, alfredsgenkins requested changes

2021-02-15 11:04 UTC, alfredsgenkins commented on src/Model/Resolver/EntityUrl.php
> +    }
This triggers the load of product from DB every time, do we really need it?

2021-02-15 11:04 UTC, alfredsgenkins commented on src/Model/Resolver/EntityUrl.php
Now this is dirty, can you please try writing that in some less **iffy** way? switch? Maybe also move the product type obtaining into separate function?

2021-02-25 10:07 UTC, merged